<?php

/**
 * @file
 * Contains examquiz.module.
 */

use Drupal\node\Entity\Node;
use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_help().
 */
function examquiz_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the examquiz module.
    case 'help.page.examquiz':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is the exam quiz module') . '</p>';
      return $output;

    default:
  }
}

function examquiz_theme() {
  return [
    'node__exam' => [
      'base hook' => 'node',
    ],
    'node__question' => [
      'base hook' => 'node'
    ]
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function examquiz_preprocess_node(&$variables) {
 

}
